version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Expone el puerto 80 del contenedor en el puerto 4200 del host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
